# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe9d2a1eade9519da882c56479ca9ac9c26711910a34ce1864e0da3ad990485817e307b90ac73358f2f6a1e90517c82221ab331f79cb71d75d8d5ab8c860722

test:
  secret_key_base: dd7fb30f3b10c15567ff256d44bca9693504f57b3eb4078dd08b4ebd83c81ac1130cfdf4a8e14ef07e16389707ae4fa455742083174e2e924fb0d43c66c810f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
